/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
// No longer need 'import * as THREE from "three"'

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb");
  const screensRef = useRef();
  const matcapTexture = useTexture("/images/textures/mat1.png");

  // All the 'new THREE.Mesh...' materials have been removed.
  // We will define them directly in the JSX below.

  return (
    <group {...props} dispose={null}>
      {/* The Bloom effect is set up perfectly!
        This only makes the mesh with 'screensRef' glow.
      */}
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={1.5}
          luminanceThreshold={0.2}
          luminanceSmoothing={0.9}
          blendFunction={BlendFunction.ADD}
        />
      </EffectComposer>

      {/* Here, we replace the material prop with a nested material.
        This is the declarative, performant R3F way.
      */}

      <mesh geometry={nodes._________6_blinn1_0.geometry}>
        <meshPhongMaterial color="#d90429" />
      </mesh>
      
      <mesh geometry={nodes.body1_blinn1_0.geometry}>
        {/* Use meshMatcapMaterial for matcaps! */}
        <meshMatcapMaterial matcap={matcapTexture} />
      </mesh>
      
      <mesh geometry={nodes.cabin_blinn1_0.geometry}>
        {/* I'll use meshStandardMaterial for better lighting, but phong is fine */}
        <meshStandardMaterial color="#582f0e" />
      </mesh>
      
      <mesh geometry={nodes.chair_body_blinn1_0.geometry}>
        <meshPhongMaterial color="#000" />
      </mesh>
      
      <mesh geometry={nodes.comp_blinn1_0.geometry}>
        <meshStandardMaterial color="#fff" />
      </mesh>
      
      {/* This is the emissive screen that will glow */}
      <mesh
        ref={screensRef}
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />
      
      <mesh
        geometry={nodes.handls_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={materials.blinn1}
     />
      <mesh
        geometry={nodes.miuse_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={materials.blinn1}
      />
      
      <mesh geometry={nodes.pillows_blinn1_0.geometry}>
        <meshPhongMaterial color="#8338ec" />
      </mesh>
      
      <mesh
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={materials.blinn1}
      />
      
      <mesh geometry={nodes.radiator_blinn1_0.geometry}>
        <meshPhongMaterial color="#fff" />
      </mesh>
      
      <mesh
        geometry={nodes.radiator_blinn1_0001.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.railing_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.stylus_blinn1_0.geometry}
        material={materials.blinn1}
      />
      
      <mesh geometry={nodes.table_blinn1_0.geometry}>
        <meshStandardMaterial color="#582f0e" />
      </mesh>
      
      <mesh
        geometry={nodes.tablet_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.triangle_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vires_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  );
}

useGLTF.preload("/models/optimized-room.glb");